version: '3.7'

services:
  database:
    image: postgres
    container_name: email-service-database
    restart: always
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: "docker"
        POSTGRES_PASSWORD: "docker"
        POSTGRES_DB: "email-service"
    volumes:
      - pgdata:/data/postgres
  api:
    container_name: email-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/app
    ports:
      - 3333:3333
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local